### ISSUE TITLE
Package build fails on Arch

### ISSUE THREAD

**Issue by xhpohanka** [ros-melodic-arch/ros-melodic-class-loader#1] opened 2020-08-17 11:21 UTC
This is what I get during `yay -S ros-melodic-desktop`

```
$ LC_ALL=C makepkg 
==> Making package: ros-melodic-class-loader 0.4.1-2 (Mon Aug 17 13:20:03 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found ros-melodic-class-loader-0.4.1.tar.gz
==> Validating source files with sha256sums...
    ros-melodic-class-loader-0.4.1.tar.gz ... Passed
==> Extracting sources...
  -> Extracting ros-melodic-class-loader-0.4.1.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Found Boost: /lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: thread system 
-- Using CATKIN_DEVEL_PREFIX: /home/honza/.cache/yay/ros-melodic-class-loader/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using default Python package layout
-- Using empy: /usr/lib/python3.8/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/honza/.cache/yay/ros-melodic-class-loader/src/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /bin/nosetests-3.8
-- catkin 0.7.26
-- BUILD_SHARED_LIBS is on
-- Searching for Poco library...
--   Found Poco!
-- components found: Foundation.
-- Found Boost: /lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: thread 
CMake Error at /home/honza/.cache/yay/ros-melodic-class-loader/src/build/devel/share/class_loader/cmake/class_loaderConfig.cmake:113 (message):
  Project 'class_loader' specifies '/include' as an include dir, which is not
  found.  It does neither exist as an absolute directory nor in
  '/home/honza/.cache/yay/ros-melodic-class-loader/src/class_loader-0.4.1//include'.
  Check the issue tracker 'https://github.com/ros/class_loader/issues' and
  consider creating a ticket if the problem has not been reported yet.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  test/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/honza/.cache/yay/ros-melodic-class-loader/src/build/CMakeFiles/CMakeOutput.log".
See also "/home/honza/.cache/yay/ros-melodic-class-loader/src/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Ratatinator97** [comment] 2020-11-16 10:25
I have it too, did someone managed to fix it ?

**Comment by bionade24** [comment] 2020-11-16 11:29
This issue is caused by a dirty build environment. The package itself builds fine on the CI https://abs-cd.oscloud.info/cd_manager/ros-melodic-class-loader

Am Montag, 16. November 2020 schrieb Alexandros SIDIRAS:

**Comment by bionade24** [comment] 2020-11-16 12:56
Will close this because it doesn't, please build in clean chroots.

**Closed as completed by bionade24** 2020-11-16 12:56 UTC
